### ISSUE TITLE
iOS build: IL2CPP error for type 'Notifications.GameNotificationChannel' in assembly SafeArray element type Int64 is not supported

### ISSUE THREAD

**Issue by alankarmisra** [Unity-Technologies/NotificationsSamples#18]
macOS Mojave, 10.14.6, Unity 2019.2.1f1, Mobile Notifications preview .6 - 1.0.3, trying to compile for iOS and I get:

IL2CPP error for type 'Notifications.GameNotificationChannel' in assembly '/projectDirectory/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll'
Additional information: SafeArray element type Int64 is not supported.

Failed running /Applications/Unity/Hub/Editor/2019.2.1f1/Unity.app/Contents/il2cpp/build/il2cppcore/il2cppcore.dll --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --profiler-report --map-file-parser="/Applications/Unity/Hub/Editor/2019.2.1f1/Unity.app/Contents/Tools/MapFileParser/MapFileParser" --directory="/projectDirectory/Temp/StagingArea/Data/Managed" --generatedcppdir="/projectDirectory/Temp/il2cppOutput/il2cppOutput" 

stdout:
IL2CPP error for type 'Notifications.GameNotificationChannel' in assembly '/projectDirectory/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll'
Additional information: SafeArray element type Int64 is not supported.
il2cpp.exe didn't catch exception: System.NotSupportedException: SafeArray element type Int64 is not supported.
at Unity.IL2CPP.Marshaling.MarshalInfoWriters.ComSafeArrayMarshalInfoWriter.GetElementVariantType(MetadataType metadataType)
at Unity.IL2CPP.Marshaling.MarshalInfoWriters.ComSafeArrayMarshalInfoWriter..ctor(ArrayType type)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.CreateMarshalInfoWriter(TypeReference type, MarshalType marshalType, MarshalInfo marshalInfo, Boolean useUnicodeCharSet, Boolean forByReferenceType, Boolean forFieldMarshaling, Boolean forReturnValue, Boolean forNativeToManagedWrapper, HashSet`1 typesForRecursiveFields)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.<>c__DisplayClass1_0.<CreateMarshalInfoWriter>b__1(FieldDefinition field)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.CreateMarshalInfoWriter(TypeReference type, MarshalType marshalType, MarshalInfo marshalInfo, Boolean useUnicodeCharSet, Boolean forByReferenceType, Boolean forFieldMarshaling, Boolean forReturnValue, Boolean forNativeToManagedWrapper, HashSet`1 typesForRecursiveFields)
at Unity.IL2CPP.SourceWriter.WriteMarshalingDefinitions(IGeneratedMethodCodeWriter writer, TypeReference type, IInteropDataCollector interopDataCollector)
at Unity.IL2CPP.SourceWriter.<>c__DisplayClass7_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`1 writeHeaderAction, Action`2 writeItemAction, Action`1 writeFooterAction, SourceWritingContext sourceWritingContext, Action`2 writeEnd)
at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext, Action`2 writeEnd)
at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, AssemblyDefinition assemblyDefinition, IMethodCollector methodCollector)
at Unity.IL2CPP.AssemblyConverter.Apply()
at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
at il2cpp.Program.DoRun(String[] args)
at il2cpp.Program.Run(String[] args)
at il2cpp.Program.Main(String[] args)
stderr:

Unhandled Exception: System.NotSupportedException: SafeArray element type Int64 is not supported.
at Unity.IL2CPP.Marshaling.MarshalInfoWriters.ComSafeArrayMarshalInfoWriter.GetElementVariantType(MetadataType metadataType)
at Unity.IL2CPP.Marshaling.MarshalInfoWriters.ComSafeArrayMarshalInfoWriter..ctor(ArrayType type)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.CreateMarshalInfoWriter(TypeReference type, MarshalType marshalType, MarshalInfo marshalInfo, Boolean useUnicodeCharSet, Boolean forByReferenceType, Boolean forFieldMarshaling, Boolean forReturnValue, Boolean forNativeToManagedWrapper, HashSet`1 typesForRecursiveFields)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.<>c__DisplayClass1_0.<CreateMarshalInfoWriter>b__1(FieldDefinition field)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at Unity.IL2CPP.Marshaling.MarshalDataCollector.CreateMarshalInfoWriter(TypeReference type, MarshalType marshalType, MarshalInfo marshalInfo, Boolean useUnicodeCharSet, Boolean forByReferenceType, Boolean forFieldMarshaling, Boolean forReturnValue, Boolean forNativeToManagedWrapper, HashSet`1 typesForRecursiveFields)
at Unity.IL2CPP.SourceWriter.WriteMarshalingDefinitions(IGeneratedMethodCodeWriter writer, TypeReference type, IInteropDataCollector interopDataCollector)
at Unity.IL2CPP.SourceWriter.<>c__DisplayClass7_0.<WriteMethodSourceFiles>b__0(IGeneratedMethodCodeWriter writer, TypeReference type)
at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`1 writeHeaderAction, Action`2 writeItemAction, Action`1 writeFooterAction, SourceWritingContext sourceWritingContext, Action`2 writeEnd)
at Unity.IL2CPP.SourceWriter.WriteEqualSizedChunks[T](NPath outputDir, IEnumerable`1 items, String fileName, Int64 chunkSize, Action`2 writeItemAction, SourceWritingContext sourceWritingContext, Action`2 writeEnd)
at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles(NPath outputDirectory, SourceWritingContext sourceWritingContext, String fileName, IEnumerable`1 typeList, IMethodCollector methodCollector, Boolean writeMarshalingDefinitions)
at Unity.IL2CPP.SourceWriter.Write(NPath outputDir, SourceWritingContext sourceWritingContext, AssemblyDefinition assemblyDefinition, IMethodCollector methodCollector)
at Unity.IL2CPP.AssemblyConverter.Apply()
at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies(IEnumerable`1 assemblyDirectories, IEnumerable`1 explicitAssemblies, NPath outputDir, NPath dataFolder, NPath symbolsFolder, NPath executableAssembiesFolder, NPath monoLibFolder, NPath monoEtcFolder, NPath[] searchDirectories, String entryAssemblyName, NPath[] extraTypesFiles)
at il2cpp.Program.DoRun(String[] args)
at il2cpp.Program.Run(String[] args)
at il2cpp.Program.Main(String[] args)
at Program.Main(String[] args) in /Users/builduser/buildslave/unity/build/External/il2cpp/il2cpp/il2cppcore/Program.cs:line 24

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunProgram(Program, String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:126)
UnityEditorInternal.Runner:RunNetCoreProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:77)
UnityEditorInternal.IL2CPPBuilder:RunIl2CppWithArguments(List`1, Action`1, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:500)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(String, String, String, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:483)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:334)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:63)
UnityEngine.GUIUtility:processEvent(Int32, IntPtr)

**Comment by qwyt** [comment]
This is a bug in Unity IL2CPP (https://issuetracker.unity3d.com/product/unity/issues/guid/1173310/) it should be fixed in the next patch release.

**Comment by vaidas-unity** [comment]
Closing as this bug has been fixed in Unity 2019.3 onwards.
