### ISSUE TITLE
UnsatisfiedLinkError uppon Push-Notification-Send

### ISSUE THREAD

**Issue by PrieDayThor** [Unity-Technologies/NotificationsSamples#5]
Hey there,

after I send a push notification I get the Exception "No implementation found for java.lang.Object com.unity3d.player.ReflectionHelper.nativeProxyInvoke". The Push-Notification works fine but the app crashes after that.

Do you know how to fix it?

``` c#
StackTrace:
"04-09 10:29:05.218 24685-24685/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.testproject, PID: 24685
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2018.3.9f1
    Device model      : samsung SM-G850F
    Device fingerprint: samsung/sltexx/slte:5.0.2/LRX22G/G850FXXS2CQD3:user/release-keys
    
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.unity3d.player.ReflectionHelper.nativeProxyInvoke(int, java.lang.String, java.lang.Object[]) (tried Java_com_unity3d_player_ReflectionHelper_nativeProxyInvoke and Java_com_unity3d_player_ReflectionHelper_nativeProxyInvoke__ILjava_lang_String_2_3Ljava_lang_Object_2)
        at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
        at com.unity3d.player.ReflectionHelper.a(Unknown Source)
        at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source)
        at java.lang.reflect.Proxy.invoke(Proxy.java:397)
        at $Proxy11.onSentNotification(Unknown Source)
        at com.unity.androidnotifications.UnityNotificationManager.sendNotification(UnityNotificationManager.java:544)
        at com.unity.androidnotifications.UnityNotificationManager.onReceive(UnityNotificationManager.java:733)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3107)
        at android.app.ActivityThread.access$1800(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1551)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6117)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)"
```

Sometimes the app crashes and sometime it doesn't. Upgrading to the newest Unity-Version couldn't fix the problem.

**Comment by PrieDayThor** [comment]
The issue has been resovled by updating to the newest Unity3D-Version (2018.3.12f1)

**Comment by PrieDayThor** [comment]
Guess I found the solution.

If you look into the AndroidNotificationsPlatform-Class you will notice that the DefaultChannelId is never used. Since I forgot to add the channel id in my notification the channel id was empty. 

Solution for that would be something like this 
``` c#
ScheduleNotification(AndroidGameNotification gameNotification)
{
   ...
   if (string.IsNullOrEmpty(gameNotification.DeliveredChannel))
   {
       gameNotification.DeliveredChannel = DefaultChannelId;
   }
   ...
}
```

Fixed it temporarily by using the following code after creating a new notification.

``` c#
#if  UNITY_ANDROID
   ((AndroidGameNotification) notification).DeliveredChannel = "01";
#endif
```
